### ISSUE TITLE
OpenSimplex2

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [creativecreatorormaybenot/funvas#117]
Implement & publish OpenSimplex2 as a package.

Related: https://github.com/frankpepermans/fast_noise/issues/1.

**Comment by creativecreatorormaybenot** [comment]
`open_simplex_2`.

**Comment by creativecreatorormaybenot** [comment]
@Solido I have published a WIP version of the `open_simplex_2` package and implemented `OpenSimplex2F` (fast version) so far 🚀 

I have tested it and it seems to work. If you want to check if it works for you, that would be greatly appreciated 🙌   
You can find the package here: https://pub.dev/packages/open_simplex_2

---

I will finish implementing the package soon and then publish the first version (with proper README etc.) 👍

**Comment by Solido** [comment]
As a java dev I know this package very well and this is nice to find the same api in dart !
