### ISSUE TITLE
Support for non-resetting ticker

### ISSUE THREAD

**Issue by Lootwig** [creativecreatorormaybenot/funvas#200]
The implementation of the FunvasContainer does not provide an option to work with an ongoing ticker (which I'd like in order to update animation speed). Due to all relevant code not having a public-facing API, the only option is currently to copy the entire package's code and change that method, if I'm not missing anything.

**Comment by creativecreatorormaybenot** [comment]
Hi @Lootwig, thanks for opening the issue! What exactly do you mean by saying "ongoing ticker"?

**Comment by creativecreatorormaybenot** [comment]
@Lootwig What is it that you are trying to accomplish?

**Comment by Lootwig** [comment]
I want to change the speed of an ongoing animation while it is still running. The speed is determined by calculating object positions in u(t) via t * factor, and I'm updating the factor via a valuelistenable.

**Comment by creativecreatorormaybenot** [comment]
@Lootwig I do not think the package needs an adjustment for this. There are two ways of doing this currently.

1. Customize your animation code to weight `t` differently.
2. Use `FunvasPainter` directly by passing a custom `ValueListenable`. You can use the `FunvasContainer` code for reference to understand how to work with `FunvasPainter`.

Note that I exposed `FunvasPainter` in #198 two months ago. I unfortunately missed publishing this update as the CD (workflow) encountered an error.

**Comment by creativecreatorormaybenot** [comment]
Resolved by #202 - @Lootwig please lmk if you have any further questions.
